#!/bin/sh

# Parse options
while [[ $# > 0 ]]
do
key="$1"
case ${key} in
    # Escape for scripts which eval the output of this script
    -e|--escape)
    escape_sep=1
    ;;
esac
shift
done

dir=${AB_DIR:-/opt/agent-bond}
sep="="

# Options separators defined to avoid clash with fish-pepper templating
ab_open_del="{""{"
ab_close_del="}""}"
if [ x$escape_sep != x ]; then
  ab_open_del='\{\{'
  ab_close_del='\}\}'
fi

if [ -z ${AB_OFF+x} ]; then
   opts="-javaagent:$dir/agent-bond.jar"
   config=${AB_CONFIG:-$dir/agent-bond.properties}
   if [ -f "$AB_CONFIG" ]; then
      # Configuration takes precedence
      opts="${opts}${sep}${AB_CONFIG}"
      sep=","
   fi
   if [ -z ${AB_ENABLED+x} ] || [ x${AB_ENABLED} != x${AB_ENABLED/jolokia/} ]; then
     # Direct options only if no configuration is found
     jsep=""
     jolokia_opts=""
     if [ -n "${AB_JOLOKIA_CONFIG}" ] && [ -f "${AB_JOLOKIA_CONFIG}" ]; then
        jolokia_opts="${jolokia_opts}${jsep}config=${AB_JOLOKIA_CONFIG}"
        jsep=","
        grep -q -e '^host' ${AB_JOLOKIA_CONFIG} && host_in_config=1
     fi
     if [ -z ${AB_JOLOKIA_HOST+x} ] && [ -z ${host_in_config+x} ]; then
        AB_JOLOKIA_HOST='0.0.0.0'
     fi
     if [ -n "$AB_JOLOKIA_HOST" ]; then
        jolokia_opts="${jolokia_opts}${jsep}host=${AB_JOLOKIA_HOST}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_PORT" ]; then
        jolokia_opts="${jolokia_opts}${jsep}port=${AB_JOLOKIA_PORT}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_USER" ]; then
        jolokia_opt="${jolokia_opts}${jsep}user=${AB_JOLOKIA_USER}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_PASSWORD" ]; then
        jolokia_opts="${jolokia_opts}${jsep}password=${AB_JOLOKIA_PASSWORD}"
        jsep=","
     fi
     # Integration of 3rd party environments
     if [ -n "$AB_JOLOKIA_AUTH_OPENSHIFT" ]; then
        jolokia_opts="${jolokia_opts}${jsep}authMode=delegate,authUrl=${AB_JOLOKIA_AUTH_OPENSHIFT%/}/users/~,authPrincipalSpec=json:metadata/user,authIgnoreCerts=true"
        jsep=","
     fi
      # Add extra opts to the end
     if [ -n "$AB_JOLOKIA_OPTS" ]; then
        jolokia_opts="${jolokia_opts}${jsep}${AB_JOLOKIA_OPTS}"
        jsep=","
     fi
     opts="${opts}${sep}jolokia${ab_open_del}${jolokia_opts}${ab_close_del}"
     sep=","
   fi
   if [ -z ${AB_ENABLED+x} ] || [ x${AB_ENABLED} != x${AB_ENABLED/jmx_exporter/} ]; then
     je_opts=""
     jsep=""
     if [ -n "$AB_JMX_EXPORTER_OPTS" ]; then
        opts="${opts}${sep}jmx_exporter${ab_open_del}${AB_JMX_EXPORTER_OPTS}${ab_close_del}"
        sep=","
     else
        port=${AB_JMX_EXPORTER_PORT-9779}
        config=${AB_JMX_EXPORTER_CONFIG-/opt/agent-bond/jmx_exporter_config.json}
        opts="${opts}${sep}jmx_exporter${ab_open_del}${port}:${config}${ab_close_del}"
        sep=","
     fi
   fi
   if [ "x$sep" != 'x=' ] ; then
     echo ${opts}
   fi
fi
