#!/bin/bash

# Global S2I variable setup
source `dirname "$0"`/s2i-setup

# Setup Jolokia to accept basic auth, using a randomly generated password that is stored
# in the container in the ${DEPLOYMENTS_DIR}/jolokia.pw file.
AB_JOLOKIA_USER="jolokia"
if [ -f "${DEPLOYMENTS_DIR}/jolokia.pw" ] ; then
	AB_JOLOKIA_PASSWORD=`cat "${DEPLOYMENTS_DIR}/jolokia.pw"`
else
	AB_JOLOKIA_PASSWORD=`tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1`
	touch "${DEPLOYMENTS_DIR}/jolokia.pw"
	chmod 600 "${DEPLOYMENTS_DIR}/jolokia.pw"
	echo $AB_JOLOKIA_PASSWORD > "${DEPLOYMENTS_DIR}/jolokia.pw"
fi
export AB_JOLOKIA_USER

# Output from assemble script
echo "Executing ${DEPLOYMENTS_DIR}/karaf/bin/karaf server ..."
if [ -z "${KARAF_OPTS}" ]; then
  KARAF_OPTS=$(/opt/jolokia/jolokia-opts)
  export KARAF_OPTS
fi

# force karaf to exec java process so docker runs a single process with PID 1
export KARAF_EXEC=exec

exec ${DEPLOYMENTS_DIR}/karaf/bin/karaf server
