#!/bin/bash

# Global S2I variable setup
source `dirname "$0"`/s2i-setup

# Read in container limits and export them as environment variables
if [ -f "${DEPLOYMENTS_DIR}/container-limits" ]; then
  source "${DEPLOYMENTS_DIR}/container-limits"
fi

# set java default options
if [ -f "${DEPLOYMENTS_DIR}/java-default-options" ]; then
  source "${DEPLOYMENTS_DIR}/java-default-options"
fi

# support JBoss Tools OpenShift debug environment variables
export JAVA_DEBUG="${JAVA_DEBUG:-${DEBUG}}"
if [ "x${JAVA_DEBUG}" != x ]; then
  export JAVA_DEBUG_PORT="${JAVA_DEBUG_PORT:-${DEBUG_PORT}}"
fi

# set debug option
if [ -f "${DEPLOYMENTS_DIR}/debug-options" ]; then
  debug_opts=$($DEPLOYMENTS_DIR/debug-options)
  if [ "x${debug_opts}" != x ]; then
    export JAVA_DEBUG_OPTS=$($DEPLOYMENTS_DIR/debug-options)
    export KARAF_DEBUG="true"
  fi
fi

# check if karaf fileinstall cfg file is present and dynamic deployment supported,
# it is disabled by default and the cfg file is removed if present
if [ -f "${DEPLOYMENTS_DIR}/karaf/etc/org.apache.felix.fileinstall-deploy.cfg" ]; then
  if [ "x${KARAF_DEPLOY}" = "x" ]; then
    rm -f "${DEPLOYMENTS_DIR}/karaf/etc/org.apache.felix.fileinstall-deploy.cfg"
  else
    echo "Dynamic deployments enabled in ${DEPLOYMENTS_DIR}/karaf/deploy"
    mkdir -p ${DEPLOYMENTS_DIR}/karaf/deploy
  fi
fi

# Output from assemble script
echo "Executing ${DEPLOYMENTS_DIR}/karaf/bin/karaf server ..."
export DEPLOYMENTS_DIR
if [ -z "${KARAF_OPTS}" ]; then
  KARAF_OPTS="$(/opt/jolokia/jolokia-opts) $(/opt/prometheus/prometheus-opts)"
  export KARAF_OPTS
fi

# Update the jboss user UID entry in /etc/passwd
sed "/^jboss/s/[^:]*/$(id -u)/3" /etc/passwd > /tmp/passwd
cat /tmp/passwd > /etc/passwd
rm /tmp/passwd

# force karaf to exec java process so docker runs a single process with PID 1
export KARAF_EXEC=exec

exec ${DEPLOYMENTS_DIR}/karaf/bin/karaf server
