#!/bin/sh

# Global S2I variable setup
source `dirname "$0"`/s2i-setup

# Maven arguments setting up the environment
maven_env_args="-Dmaven.repo.local=${S2I_ARTIFACTS_DIR}/m2"

# =========================================================================
# Helper functions:

function check_error() {
  local label=$1
  local error=$2
  if [ ${error} -ne 0 ]; then
    echo "Aborting due to error code $error for $label"
    exit ${error}
  fi
}

function get_output_dir() {
  local dir=""

  # If multi module build and no ARTIFACT_DIR is set --> error
  if [ x"${ARTIFACT_DIR}" = x ]; then
    echo " ${MAVEN_ARGS} ${MAVEN_ARGS_APPEND}" | grep -q ' -pl'
    if [ $? -eq 0 ]; then
       echo "ARTIFACT_DIR must be set for multi module Maven builds"
       exit 1
    fi
    dir="${S2I_SOURCE_DIR}/target"
  else
    if [ "${ARTIFACT_DIR:0:1}" = "/" ]; then
       echo "ARTIFACT_DIR \"${ARTIFACT_DIR}\" must not be absolute but relative to the source directory"
       exit 1
    fi
    dir="${S2I_SOURCE_DIR}/${ARTIFACT_DIR}"
  fi

  # Normalize dir
  dir=$(echo ${dir} | tr -s /)
  dir=${dir%/}
  # The parent must exist but target/ won't exist yet
  if [ ! -d $(dirname "${dir}"}) ]; then
    echo "Please specify an existing build directory ARTIFACT_DIR (tried '$(dirname "${dir}")' which does not exist)"
    exit 1
  fi
  echo ${dir}
}

function copy_dir() {
  local src=$1
  local dest=$2
  
  # Copy recursively and preserve ownership: -a
  cp -a ${src}/* ${dest}
}

function copy_fat_jar() {
  local dir=$1
  local dest=$2

  # Filter out temporary jars from the shade plugin which start with 'original-'
  local old_dir=$(pwd)
  cd ${dir}
  if [ $? = 0 ]; then
    local nr_jars=`ls *.jar 2>/dev/null | grep -v '^original-' | wc -l | tr -d '[[:space:]]'`
    if [ ${nr_jars} = 1 ]; then
      local fat_jar=$(ls *.jar | grep -v '^original-')

      # Copy and preserve ownership: -a
      cd ${old_dir}
      cp -a ${dir}/${fat_jar} ${dest}
      return
    fi
    echo "ERROR: Found ${nr_jars} jars in ${dir} (1 expected): $(ls *.jar | grep -v '^original' | tr '\n' ' ')"
    cd ${old_dir}
    exit 1
  else
    cd ${old_dir}
    echo "ERROR: No directory ${dir} found for auto detection"
    exit 1
  fi
}


function setup_maven() {
  if [ -f "${S2I_SOURCE_DIR}/configuration/settings.xml" ]; then
    maven_env_args="${maven_env_args} -s ${S2I_SOURCE_DIR}/configuration/settings.xml"
    echo "Using custom maven settings from ${S2I_SOURCE_DIR}/configuration/settings.xml"
  fi
}

function build_maven() {
  # Where artifacts are created during build
  local build_dir=$1

  # Where to put the artifacts
  local app_dir=$2

  # Default args: no tests, if a module is specified, only build this module
  local maven_args=${MAVEN_ARGS:-package -DskipTests -e}

  echo "Found pom.xml ... "
  echo "Running 'mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}'"

  local old_dir=$(pwd)
  cd ${S2I_SOURCE_DIR}
  check_error "changing directory to ${S2I_SOURCE_DIR}" $?

  # =========
  # Run Maven
  mvn ${maven_env_args} --version
  mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}
  check_error "Maven build" $?

  # ==============
  # Copy artifacts
  if [ -d "${build_dir}/hawt-app" ]; then
    echo "Hawtapp plugin detected. Copying Maven artifacts from ${build_dir}/hawt-app to ${app_dir} ..."
    copy_dir "${build_dir}/hawt-app" ${app_dir}
    check_error "copying ${build_dir}/hawt-app to ${app_dir}" $?
  else
    echo "Copying fat-jar to ${app_dir} ..."
    copy_fat_jar ${build_dir} ${app_dir}
    check_error "copying fat jar from ${build_dir} to ${app_dir}" $?

    echo "Copying java-run scripts into app folder ..."
    cp -r /opt/run-java/* ${app_dir}
    check_error "cannot copy java-run scripts from /usr/local/run-java to ${app_dir}" $?

    echo "Changing permissions of bin scripts ..."
    chmod 755 ${app_dir}/*.sh ${app_dir}/java-container-options
    check_error "cannot change permissions on  run-java files in ${app_dir}" $?
  fi

  # ======================
  # Remove repo if desired
  if [ "x${MAVEN_CLEAR_REPO}" != "x" ]; then
    rm -rf "${S2I_ARTIFACTS_DIR}/m2"
    check_error "Cannot remove local Maven repository ${S2I_ARTIFACTS_DIR}/m2" $?
  fi

  cd ${old_dir}
}

# =========================================================================
# Main

echo "=================================================================="
echo "Starting S2I Java Build ....."
build_dir=$(get_output_dir)
check_error "Cannot get output dir: $build_dir" $?
if [ -f "${S2I_SOURCE_DIR}/pom.xml" ]; then
  echo "Maven build detected"
  # If a pom.xml is present use maven
  setup_maven
  build_maven ${build_dir} ${DEPLOYMENTS_DIR}
else
  binary_dir="${ARTIFACT_DIR:-${S2I_SOURCE_DIR}/deployments}"
  # Assuming that the source already contains compiled artefacts
  echo "Copying binaries from ${binary_dir} to ${S2I_ARTIFACTS_DIR} ..."
  copy_dir ${binary_dir} ${DEPLOYMENTS_DIR}
  check_error "copying ${binary_dir} to ${DEPLOYMENTS_DIR}" $?
fi

echo "... done"
